name: CI Build
run-name: ${{ github.actor }} pushed a commit 🚀
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.4.0"]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Run image
        # uses: abatilo/actions-poetry@v2
        # with:
        #   poetry-version: ${{ matrix.poetry-version }}
      - name: poetry install
        run: poetry --help
      - name: build
        run: poetry build

            
      
      