name: GitHub Actions Demo
run-name: ${{ github.actor }} pushed a commit 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: make build
      
      