name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml@main
    with:
      python-version: 3.9
      poetry-version: 1.4.0
      os: ubuntu-latest
      